# Generated by Django 5.1.1 on 2025-06-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antennas",
            name="number",
            field=models.IntegerField(max_length=500, unique=True),
        ),
    ]
