# Generated by Django 5.1.1 on 2025-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0002_alter_antennas_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antennas",
            name="number",
            field=models.BigIntegerField(unique=True),
        ),
    ]
