# Generated by Django 5.1.1 on 2025-06-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0004_antennas_open_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="antennas",
            name="status",
            field=models.CharField(default="Offline", max_length=50),
        ),
    ]
