# Generated by Django 5.1.1 on 2025-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=64, unique=True)),
                ("owner_name", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
