# Generated by Django 5.1.1 on 2025-06-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0004_antennas_open_time"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "antenna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antenna_permissions",
                        to="setting.antennas",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_permissions",
                        to="tag.tag",
                    ),
                ),
            ],
        ),
    ]
