# Generated by Django 5.1.1 on 2025-06-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0004_antennas_open_time"),
        ("tag", "0003_alter_tagpermission_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagpermission",
            name="tag",
        ),
        migrations.AddField(
            model_name="tag",
            name="rules",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags_permissions",
                to="tag.tagpermission",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="tagpermission",
            name="antenna",
        ),
        migrations.AddField(
            model_name="tagpermission",
            name="antenna",
            field=models.ManyToManyField(
                related_name="antenna_permissions", to="setting.antennas"
            ),
        ),
    ]
