# Generated by Django 5.1.1 on 2025-06-08 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0004_remove_tagpermission_tag_tag_rules_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="rules",
            new_name="rule",
        ),
    ]
