# Generated by Django 5.1.1 on 2025-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0006_alter_tagpermission_antenna"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
