# Generated by Django 5.1.1 on 2025-07-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0007_tag_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="car_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="number_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="pelicula",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
