# Generated by Django 5.1.1 on 2025-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0008_tag_car_name_tag_number_unit_tag_pelicula"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tag_number",
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="owner_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
