# Generated by Django 5.1.1 on 2025-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0009_tag_tag_number_alter_tag_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_number",
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
