# Generated by Django 5.1.1 on 2025-07-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0010_alter_tag_tag_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_permissions', to='tag.tagpermission'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
