# Generated by Django 5.1.1 on 2025-06-22 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnonymousTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid_anonymousTag", models.CharField(max_length=255)),
                (
                    "time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            6,
                            22,
                            14,
                            56,
                            47,
                            943241,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
    ]
