# Generated by Django 5.1.1 on 2025-06-22 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymoustag",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 22, 14, 56, 57, 909827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
