# Generated by Django 5.1.1 on 2025-06-22 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0002_alter_anonymoustag_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymoustag",
            name="time",
        ),
        migrations.AddField(
            model_name="anonymoustag",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
