# Generated by Django 5.1.1 on 2025-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0003_remove_anonymoustag_time_anonymoustag_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymoustag",
            name="create_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
