# Generated by Django 5.1.1 on 2025-07-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0004_alter_anonymoustag_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymoustag",
            name="antenna",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
