# Generated by Django 5.1.1 on 2025-07-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tag", "0008_tag_car_name_tag_number_unit_tag_pelicula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=64)),
                ("create_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_logs",
                        to="tag.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
    ]
