# Generated by Django 5.1.1 on 2025-07-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-create_at'], 'verbose_name': 'لاگ', 'verbose_name_plural': 'لاگ\u200cها'},
        ),
        migrations.RemoveField(
            model_name='logs',
            name='tag',
        ),
        migrations.AddField(
            model_name='logs',
            name='car_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='door',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='owner_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='rule',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='tag_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='unit_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
